# Generated by Django 4.0 on 2022-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_thumbnail_deliveryorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
    ]
